import { Hero } from "./types";

export const HERO_DATABASE: Hero[] = [
  {
    id: "melia",
    name: "Melia",
    ability:
      "Defense-Based Damage, Fixed Damage, Defense Boost, Magic Vulnerability, Increased Miss Chance, Crowd Control Immunity, Revive, Taunt, Physical Enhancement - Crystal Dragon, Magic Bond, Crystal Resonance",
    attackType: "Magic",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "gelidus",
    name: "Gelidus",
    ability:
      "Extreme Chill, Freeze, Damage Resistance, Heal, Block Rate Boost, Effect Probability Reduction, Ignore Defense",
    attackType: "Physical",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "freyja",
    name: "Freyja",
    ability:
      "Magic Attack Boost, Effect Hit Rate Boost, Bleed, Blessing, Barrier, Ignore Defense, HP Alteration",
    attackType: "Magic",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "trude",
    name: "Trude",
    ability:
      "Crit Damage Boost, Block Rate Boost, Crowd Control Immunity, Revive, Pain Endurance, Barrier, Heal",
    attackType: "Physical",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "wukong",
    name: "Wukong",
    ability:
      "Clone, Skill Effects Change (Clone Presence), Petrify, Crit Rate Boost (100% at 6th Transcendence), Ignore Defense, Cooldown Reduction (On Damage Taken), Heal All Allies (On Skill Activation / HP Below Half), Damage Resistance, Guts, Attack Power-Based Defense Boost, Crowd Control Immunity",
    attackType: "Magic",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "ryan",
    name: "Ryan",
    ability:
      "3体攻撃スキル与ダメ上昇, Blind, Burn Immunity, Damage Immunity, Taunt, Cooldown Reduction",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "SS",
  },
  {
    id: "elysia",
    name: "Elysia",
    ability:
      "Fixed Damage, Increased Miss Chance, Silence, Reduced Buff Duration, Debuff Removal, Damage Immunity",
    attackType: "Physical",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "kyrielle",
    name: "Kyrielle",
    ability:
      "Magic Damage Boost, Paralysis, Crowd Control Immunity, Debuff Removal, Damage Nullification, Guts, Ignore Defense",
    attackType: "Magic",
    range: "All Enemies",
    tier: "SS",
  },
  {
    id: "kyle",
    name: "Kyle",
    ability:
      "Max HP-Based Damage, Crit Rate Boost, Buff Removal, Damage Nullification, Pierce, Ignore Defense, Eyes of the Strong",
    attackType: "Physical",
    range: "4 Enemies",
    tier: "SSS",
  },
  {
    id: "aquila",
    name: "Aquila",
    ability:
      "Max HP-Based Damage, Weakness Hit Chance Reduction, Effect Resist Reduction, Death, Link, Heal, Cooldown Reduction, Death Turn Reduction",
    attackType: "Physical",
    range: "All Enemies",
    tier: "SS",
  },
  {
    id: "amelia",
    name: "Amelia",
    ability:
      "Effect Hit Rate Boost, Unable to Recover, Debuff Removal, Revive, HP Alteration",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "S+",
  },
  {
    id: "kagura",
    name: "Kagura",
    ability:
      "Crit Damage Boost, Physical Damage Boost, Physical Vulnerability, Incoming Healing Reduction, Petrify, Debuff Removal, Indomitable, Heal",
    attackType: "Physical",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "klahan",
    name: "Klahan",
    ability:
      "Physical Attack Boost, Physical Damage Boost, All Damage Reduction, Damage Immunity, Heal, Pierce",
    attackType: "Physical",
    range: "All Enemies",
    tier: "S+",
  },
  {
    id: "miho",
    name: "Miho",
    ability:
      "Weakness Hit Damage Boost, Magic Vulnerability, Reduced Buff Duration, Debuff Removal, Guts, Life Drain",
    attackType: "Magic",
    range: "3 Enemies",
    tier: "SS",
  },
  {
    id: "orly",
    name: "Orly",
    ability:
      "Max HP-Based Damage, Crit Rate Boost, Crit Damage Boost, Defense Reduction, Buff Removal, Debuff Removal, Damage Nullification, Continuous Healing",
    attackType: "Magic",
    range: "All Enemies",
    tier: "SS",
  },
  {
    id: "daisy",
    name: "Daisy",
    ability:
      "Max HP-Based Damage, Magic Attack Boost, Petrify Immunity, Buff Removal, Barrier",
    attackType: "Magic",
    range: "All Enemies",
    tier: "S+",
  },
  {
    id: "colt",
    name: "Colt",
    ability:
      "Effect Hit Rate Boost, All Attack Reduction, Guts, Camouflage, Cooldown Reduction, Bomb",
    attackType: "Physical",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "biscuit",
    name: "Biscuit",
    ability:
      "Defense-Based Damage, Weakness Hit Chance Boost, Quintuple-Target Attack Resistance, Boss DMG, Defense Reduction, All Damage Reduction, Buff Removal, Ignore Defense",
    attackType: "Magic",
    range: "3 Enemies",
    tier: "SS",
  },
  {
    id: "platin",
    name: "Platin",
    ability:
      "Defense-Based Damage, Fixed Damage, All Attack Reduction, Buff Removal, Heal, Damage-Based Healing, HP Alteration",
    attackType: "Magic",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "karma",
    name: "Karma",
    ability:
      "Defense-Based Damage, Defense Boost, All Damage Boost, Damage Resistance, Block Rate Boost, All Damage Reduction, Pierce, Ignore Defense",
    attackType: "Magic",
    range: "3 Enemies",
    tier: "SS",
  },
  {
    id: "rin",
    name: "Rin",
    ability:
      "Increased Miss Chance, Reduced Buff Duration, Damage Nullification, Revive, Barrier, Cooldown Reset, Confusion",
    attackType: "Magic",
    range: "4 Enemies",
    tier: "SS",
  },
  {
    id: "mercure",
    name: "Mercure",
    ability:
      "Effect Resist Reduction, Incoming Healing Reduction, Stun, Blessing, Barrier, Magic Reflux",
    attackType: "Magic",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "yeonhee",
    name: "Yeonhee",
    ability:
      "Max HP-Based Damage, Magic Attack Boost, Magic Damage Boost, Sleep, Damage Nullification, Ignore Defense",
    attackType: "Magic",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "taka",
    name: "Taka",
    ability:
      "Crit Damage Boost, Physical Vulnerability, Damage Nullification, Ignore Defense",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "SS",
  },
  {
    id: "teo",
    name: "Teo",
    ability:
      "Physical Attack Boost, Crit Rate Boost, Reduced Buff Duration, Damage Nullification, Immortality, Pierce, Cooldown Reset",
    attackType: "Physical",
    range: "All Enemies",
    tier: "SS",
  },
  {
    id: "fai",
    name: "Fai",
    ability:
      "Max HP-Based Damage, Defense Reduction, Physical Vulnerability, Burn, Buff Removal, Revive, Barrier, Execution",
    attackType: "Physical",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "rosie",
    name: "Rosie",
    ability:
      "Self Max HP-Based Damage, Effect Probability Boost, Effect Resist Reduction, Death, Reduced Buff Duration, Damage Immunity, Guts, Revive",
    attackType: "Magic",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "juri",
    name: "Juri",
    ability:
      "Max HP-Based Damage, Defense Reduction, Crowd Control Immunity, Immortality, Follow-Up Attack, Souldeath",
    attackType: "Magic",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "evan",
    name: "Evan",
    ability:
      "Defense-Based Damage, Defense Boost, Block Rate Boost, Stun, Stun Immunity, Barrier",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "S+",
  },
  {
    id: "karin",
    name: "Karin",
    ability: "Debuff Removal, Revive, Heal",
    attackType: "Magic",
    range: "Only Basic Attack",
    tier: "B",
  },
  {
    id: "rudy",
    name: "Rudy",
    ability:
      "Defense-Based Damage, Defense Boost, Damage Resistance, Stun, Crowd Control Immunity, Reduced Buff Duration, Debuff Removal, Link",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "SS",
  },
  {
    id: "rachel",
    name: "Rachel",
    ability:
      "Weakness Hit Chance Boost, All Attack Reduction, Defense Reduction, All Damage Reduction, Physical Vulnerability, Burn, Revive",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "SS",
  },
  {
    id: "eileene",
    name: "Eileene",
    ability: "Physical Attack Boost, Shock, Revive, Pierce",
    attackType: "Physical",
    range: "All Enemies",
    tier: "S+",
  },
  {
    id: "spike",
    name: "Spike",
    ability:
      "Self Max HP-Based Damage, Effect Hit Rate Boost, Effect Resist Boost, Freeze, Debuff Removal, Guts, Heal",
    attackType: "Physical",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "jave",
    name: "Jave",
    ability:
      "Stun, Crowd Control Immunity, Burn, Counterattack, Pierce, Dragonflame",
    attackType: "Physical",
    range: "All Enemies",
    tier: "S+",
  },
  {
    id: "kris",
    name: "Kris",
    ability: "Death, Immortality, Barrier, Heal, Cooldown Reset",
    attackType: "Physical",
    range: "All Enemies",
    tier: "SS",
  },
  {
    id: "dellons",
    name: "Dellons",
    ability: "Physical Damage Boost, Silence, Damage Nullification",
    attackType: "Physical",
    range: "All Enemies",
    tier: "S+",
  },
  {
    id: "vanessa",
    name: "Vanessa",
    ability:
      "Defense Reduction, Magic Vulnerability, Petrify, Buff Removal, Damage Immunity, Pierce, Cooldown Increase",
    attackType: "Magic",
    range: "4 Enemies",
    tier: "SS",
  },
  {
    id: "ace",
    name: "Ace",
    ability:
      "Physical Attack Boost, Defense Reduction, Physical Vulnerability, Incoming Healing Reduction, Reduced Buff Duration, Debuff Removal, Guts",
    attackType: "Physical",
    range: "All Enemies",
    tier: "S+",
  },
  {
    id: "silvesta",
    name: "Silvesta",
    ability:
      "Reduced Buff Duration, Blessing, Guts, Ignore Defense, Life Drain",
    attackType: "Magic",
    range: "All Enemies",
    tier: "SSS",
  },
  {
    id: "aragon",
    name: "Aragon",
    ability:
      "Defense-Based Damage, All Attack Reduction, Crit Damage Reduction, Stun, Reduced Buff Duration, Heal, Pierce, Cooldown Reduction",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "SS",
  },
  {
    id: "ariel",
    name: "Ariel",
    ability:
      "Magic Damage Boost, Defense Reduction, Increased Miss Chance, Blind, Burn Immunity",
    attackType: "Magic",
    range: "3 Enemies",
    tier: "A+",
  },
  {
    id: "alice",
    name: "Alice",
    ability: "Defense Boost, Incoming Healing Boost, Heal, Continuous Healing",
    attackType: "Magic",
    range: "Only Basic Attack",
    tier: "S+",
  },
  {
    id: "bane",
    name: "Bane",
    ability:
      "Effect Hit Rate Boost, Physical Attack Reduction, Silence, Immortality",
    attackType: "Magic",
    range: "3 Enemies",
    tier: "B",
  },
  {
    id: "espada",
    name: "Espada",
    ability:
      "Max HP-Based Damage, Crit Rate Boost, Magic Damage Boost, Magic Resistance, Magic Vulnerability",
    attackType: "Magic",
    range: "Single Enemy",
    tier: "S+",
  },
  {
    id: "ellin",
    name: "Ellin",
    ability: "Physical Resistance, Death, Damage Immunity",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "C",
  },
  {
    id: "heavenia",
    name: "Heavenia",
    ability:
      "Physical Attack Boost, Freeze, Reduced Buff Duration, Damage Immunity",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "A+",
  },
  {
    id: "hellenia",
    name: "Hellenia",
    ability:
      "Defense-Based Damage, Defense Boost, Increased Miss Chance, Debuff Removal, Damage Immunity, Heal, Taunt",
    attackType: "Physical",
    range: "All Enemies",
    tier: "A",
  },
  {
    id: "ellen",
    name: "Ellen",
    ability: "Physical Damage Boost, Reduced Buff Duration, Damage Immunity",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "C",
  },
  {
    id: "karon",
    name: "Karon",
    ability: "Bleed Immunity, Barrier, Heal",
    attackType: "Magic",
    range: "Only Basic Attack",
    tier: "S",
  },
  {
    id: "catty",
    name: "Catty",
    ability:
      "Physical Attack Boost, Weakness Hit Chance Boost, Crit Rate Boost, Physical Vulnerability, Block Rate Reduction, Unable to Recover",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "B",
  },
  {
    id: "chloe",
    name: "Chloe",
    ability:
      "All Attack Boost, Crit Rate Boost, Unable to Recover, Shock Immunity, Buff Removal, Debuff Removal, Heal",
    attackType: "Magic",
    range: "Single Enemy",
    tier: "S",
  },
  {
    id: "coco",
    name: "Coco",
    ability: "Effect Resist Boost, Quintuple-Target Attack Resistance, Shock",
    attackType: "Magic",
    range: "Single Enemy",
    tier: "C",
  },
  {
    id: "sieg",
    name: "Sieg",
    ability:
      "Physical Attack Boost, All Damage Reduction, Stun Immunity, Ignore Defense",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "S",
  },
  {
    id: "jane",
    name: "Jane",
    ability: "Poison, Camouflage",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "A",
  },
  {
    id: "jupy",
    name: "Jupy",
    ability:
      "Crit Rate Boost, Crit Damage Boost, Poison, Camouflage, Change Skill",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "B",
  },
  {
    id: "joker",
    name: "Joker",
    ability: "Crit Damage Boost, Crit Rate Reduction, Stun, Buff Removal",
    attackType: "Magic",
    range: "3 Enemies",
    tier: "A+",
  },
  {
    id: "sylvia",
    name: "Sylvia",
    ability:
      "Magic Attack Boost, Defense Reduction, Immortality, Pierce, Ignore Defense",
    attackType: "Magic",
    range: "All Enemies",
    tier: "A",
  },
  {
    id: "jin",
    name: "Jin",
    ability:
      "Fixed Damage, Physical Attack Boost, Crit Rate Boost, Stun, Silence Immunity, Barrier",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "A+",
  },
  {
    id: "snipper",
    name: "Snipper",
    ability: "Max HP-Based Damage, Physical Damage Boost, Burn",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "A",
  },
  {
    id: "shane",
    name: "Shane",
    ability: "Crit Rate Boost, Magic Resistance, Follow-Up Attack",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "S",
  },
  {
    id: "sera",
    name: "Sera",
    ability: "Crit Rate Boost, Reduced Buff Duration",
    attackType: "Magic",
    range: "3 Enemies",
    tier: "A",
  },
  {
    id: "chancellor",
    name: "Chancellor",
    ability:
      "Defense-Based Damage, Fixed Damage, All Attack Reduction, Defense Reduction, All Damage Reduction, Increased Miss Chance, Buff Removal, Damage Immunity, Heal",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "SS",
  },
  {
    id: "nia",
    name: "Nia",
    ability:
      "Effect Hit Rate Boost, Shock, Reduced Buff Duration, Barrier, Cooldown Increase",
    attackType: "Magic",
    range: "All Enemies",
    tier: "S",
  },
  {
    id: "knox",
    name: "Knox",
    ability:
      "Self Max HP-Based Damage, Death Effect Probability Boost, Effect Resist Reduction, Death, Damage Immunity, Barrier, Taunt",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "S+",
  },
  {
    id: "noho",
    name: "Noho",
    ability:
      "Self Max HP-Based Damage, Magic Attack Boost, All Attack Reduction, Buff Removal, Barrier, HP Alteration",
    attackType: "Magic",
    range: "3 Enemies",
    tier: "B",
  },
  {
    id: "pascal",
    name: "Pascal",
    ability:
      "Magic Attack Boost, Crit Rate Boost, Crit Damage Boost, Damage Nullification, Ignore Defense, Cooldown Reset",
    attackType: "Magic",
    range: "Single Enemy",
    tier: "SS",
  },
  {
    id: "ballista",
    name: "Ballista",
    ability:
      "Fixed Damage, Damage Nullification, Camouflage, Follow-Up Attack, Pierce",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "A",
  },
  {
    id: "victoria",
    name: "Victoria",
    ability:
      "Magic Attack Boost, Physical Resistance, Magic Vulnerability, Paralysis Immunity, Heal",
    attackType: "Magic",
    range: "Single Enemy",
    tier: "S",
  },
  {
    id: "blackrose",
    name: "Black Rose",
    ability:
      "Physical Attack Boost, All Attack Boost, Petrify Immunity, Buff Removal, Heal",
    attackType: "Physical",
    range: "All Enemies",
    tier: "S",
  },
  {
    id: "velika",
    name: "Velika",
    ability:
      "Crit Rate Boost, Magic Damage Boost, Magic Vulnerability, Silence, Burn, Barrier, Cooldown Reduction",
    attackType: "Magic",
    range: "All Enemies",
    tier: "A+",
  },
  {
    id: "may",
    name: "May",
    ability:
      "Physical Damage Boost, Physical Vulnerability, Blind, Bleed, Burn, Poison, Barrier",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "A",
  },
  {
    id: "yui",
    name: "Yui",
    ability:
      "Physical Damage Boost, Magic Attack Reduction, Burn Immunity, Revive, Heal, Continuous Healing",
    attackType: "Magic",
    range: "Only Basic Attack",
    tier: "S+",
  },
  {
    id: "yuri",
    name: "Yuri",
    ability:
      "Crit Rate Boost, Magic Damage Boost, Burn, Revive, Ignore Defense",
    attackType: "Magic",
    range: "Single Enemy",
    tier: "A",
  },
  {
    id: "lania",
    name: "Lania",
    ability:
      "Magic Attack Boost, Effect Hit Rate Boost, Freeze, Freeze Immunity",
    attackType: "Magic",
    range: "All Enemies",
    tier: "A+",
  },
  {
    id: "li",
    name: "Li",
    ability:
      "Self Max HP-Based Damage, Stun, Damage Immunity, Heal, Counterattack, Taunt, HP Alteration",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "S",
  },
  {
    id: "lina",
    name: "Lina",
    ability:
      "All Damage Boost, Crit Damage Boost, Effect Resist Boost, Defense Reduction, Barrier, Heal, Continuous Healing",
    attackType: "Magic",
    range: "Single Enemy",
    tier: "SS",
  },
  {
    id: "rook",
    name: "Rook",
    ability:
      "Self Max HP-Based Damage, Crit Rate Boost, Physical Resistance, Block Rate Boost, Barrier",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "A+",
  },
  {
    id: "lucy",
    name: "Lucy",
    ability:
      "Defense-Based Damage, Defense Boost, Physical Attack Reduction, Poison Immunity, Debuff Removal, Heal, Cooldown Reduction",
    attackType: "Magic",
    range: "Only Basic Attack",
    tier: "S",
  },
  {
    id: "ruri",
    name: "Ruri",
    ability:
      "Weakness Hit Chance Boost, Magic Damage Boost, Heal, Ignore Defense",
    attackType: "Magic",
    range: "3 Enemies",
    tier: "S+",
  },
  {
    id: "rei",
    name: "Rei",
    ability: "Physical Attack Boost, Bleed, Poison, Camouflage, Pierce",
    attackType: "Physical",
    range: "All Enemies",
    tier: "A",
  },
  {
    id: "asura",
    name: "Asura",
    ability:
      "Weakness Hit Chance Boost, Defense Reduction, Barrier, Focus Target",
    attackType: "Magic",
    range: "Single Enemy",
    tier: "A+",
  },
  {
    id: "soi",
    name: "Soi",
    ability:
      "Effect Hit Rate Boost, Quintuple-Target Attack Resistance, Bleed, Reduced Buff Duration, Buff Removal",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "A",
  },
  {
    id: "bidam",
    name: "Bi Dam",
    ability: "Physical Damage Boost, Bleed, Heal, Pierce, Explosion",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "S",
  },
  {
    id: "fengyan",
    name: "Feng Yan",
    ability:
      "Crit Damage Boost, Defense Reduction, Freeze Immunity, Damage Immunity, Ignore Defense",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "S",
  },
  {
    id: "yushin",
    name: "Yu Shin",
    ability:
      "Effect Hit Rate Boost, Effect Resist Reduction, Incoming Healing Reduction, Paralysis, Debuff Removal, Damage Immunity",
    attackType: "Magic",
    range: "All Enemies",
    tier: "S",
  },
  {
    id: "ahkan",
    name: "Ahkan",
    ability: "Defense Boost, Damage Resistance, Freeze",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "C",
  },
  {
    id: "aaron",
    name: "Aaron",
    ability: "Weakness Hit Chance Boost, Incoming Healing Reduction",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "D",
  },
  {
    id: "taurus",
    name: "Taurus",
    ability: "All Attack Boost, Bleed, Revive",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "C",
  },
  {
    id: "ichi",
    name: "Ichi",
    ability: "Death, Revive, Heal",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "C",
  },
  {
    id: "wendy",
    name: "Wendy",
    ability: "All Attack Reduction, Stun, Heal",
    attackType: "Physical",
    range: "Only Basic Attack",
    tier: "D",
  },
  {
    id: "kai",
    name: "Kai",
    ability: "Physical Attack Boost, Defense Reduction, Bleed",
    attackType: "Physical",
    range: "All Enemies",
    tier: "C",
  },
  {
    id: "drillo",
    name: "Drillo",
    ability: "Defense Boost, Block Rate Boost, Debuff Removal",
    attackType: "Physical",
    range: "Only Basic Attack",
    tier: "D",
  },
  {
    id: "guppy",
    name: "Guppy",
    ability: "Effect Resist Boost, Buff Removal",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "cleo",
    name: "Cleo",
    ability:
      "Magic Attack Boost, Physical Attack Reduction, Petrify, Silence Immunity, Poison",
    attackType: "Magic",
    range: "3 Enemies",
    tier: "A+",
  },
  {
    id: "clops",
    name: "Clops",
    ability: "Stun, Heal",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "kohkun",
    name: "Kohkun",
    ability:
      "Crit Rate Boost, Physical Damage Boost, Block Rate Boost, Stun, Debuff Removal",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "C",
  },
  {
    id: "sarah",
    name: "Sarah",
    ability:
      "Defense Boost, Damage Resistance, Defense Reduction, All Damage Reduction, Sleep Immunity, Debuff Removal, Heal",
    attackType: "Magic",
    range: "3 Enemies",
    tier: "A",
  },
  {
    id: "jas",
    name: "Jas",
    ability: "Effect Hit Rate Boost, Shock",
    attackType: "Magic",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "jak",
    name: "Jak",
    ability: "Block Rate Boost, Bleed",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "jumon",
    name: "Jumon",
    ability: "Effect Hit Rate Reduction, Paralysis, Damage Immunity",
    attackType: "Magic",
    range: "All Enemies",
    tier: "C",
  },
  {
    id: "shiro",
    name: "Shiro",
    ability:
      "Defense Boost, Single-Target Attack Resistance, Reduced Buff Duration, Taunt",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "C",
  },
  {
    id: "syllops",
    name: "Syllops",
    ability: "Paralysis, Poison",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "skud",
    name: "Skud",
    ability: "Physical Damage Boost, Buff Removal",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "skull",
    name: "Skull",
    ability: "Physical Resistance, Blind",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "smoky",
    name: "Smoky",
    ability: "Physical Attack Boost, Incoming Healing Reduction, Blind",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "cellops",
    name: "Cellops",
    ability: "Bleed",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "charles",
    name: "Charles",
    ability: "Bleed",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "derek",
    name: "Derek",
    ability: "Paralysis, Poison, Revive",
    attackType: "Physical",
    range: "All Enemies",
    tier: "C",
  },
  {
    id: "toto",
    name: "Toto",
    ability: "Weakness Hit Chance Boost, Bleed",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "nami",
    name: "Nami",
    ability: "Physical Attack Boost, Buff Removal",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "howl",
    name: "Howl",
    ability: "All Damage Boost, Buff Removal, Revive",
    attackType: "Magic",
    range: "Single Enemy",
    tier: "C",
  },
  {
    id: "happy",
    name: "Happy",
    ability: "Stun",
    attackType: "Magic",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "babel",
    name: "Babel",
    ability: "Silence",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "baron",
    name: "Baron",
    ability: "Damage Resistance, Damage Immunity",
    attackType: "Physical",
    range: "Only Basic Attack",
    tier: "D",
  },
  {
    id: "pooki",
    name: "Pooki",
    ability: "Stun",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "fruna",
    name: "Fruna",
    ability: "Freeze",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "frose",
    name: "Frose",
    ability: "Defense Boost",
    attackType: "Physical",
    range: "Only Basic Attack",
    tier: "D",
  },
  {
    id: "beskin",
    name: "Beskin",
    ability: "Weakness Hit Chance Boost, Buff Removal",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "pepe",
    name: "Pepe",
    ability: "Stun, Revive, Heal",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "C",
  },
  {
    id: "bella",
    name: "Bella",
    ability: "All Damage Reduction, Effect Resist Reduction, Paralysis",
    attackType: "Magic",
    range: "Single Enemy",
    tier: "C",
  },
  {
    id: "hokin",
    name: "Hokin",
    ability:
      "Physical Attack Boost, Physical Damage Boost, Defense Reduction, Stun, Damage Immunity",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "C",
  },
  {
    id: "popo",
    name: "Popo",
    ability: "Incoming Healing Reduction",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "ponpon",
    name: "PonPon",
    ability: "Crit Rate Boost, Reduced Buff Duration",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "yumi",
    name: "Yumi",
    ability: "Unable to Recover, Damage Immunity, Pierce",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "C",
  },
  {
    id: "rocky",
    name: "Rocky",
    ability: "Effect Hit Rate Boost, Blind",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "rahkun",
    name: "Rahkun",
    ability:
      "Defense-Based Damage, Defense Boost, Effect Resist Boost, Physical Resistance, Block Rate Boost, Barrier, Taunt",
    attackType: "Physical",
    range: "Only Basic Attack",
    tier: "C",
  },
  {
    id: "ricky",
    name: "Ricky",
    ability: "Bleed",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "reaper",
    name: "Reaper",
    ability: "Bleed",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "leo",
    name: "Leo",
    ability:
      "All Attack Boost, Defense Reduction, All Damage Reduction, Bleed, Death Immunity, Revive, Life Drain",
    attackType: "Physical",
    range: "3 Enemies",
    tier: "S+",
  },
  {
    id: "rowl",
    name: "Rowl",
    ability: "Crit Rate Boost, Incoming Healing Reduction",
    attackType: "Physical",
    range: "Single Enemy",
    tier: "D",
  },
  {
    id: "loto",
    name: "Loto",
    ability: "Crit Rate Boost, Incoming Healing Reduction",
    attackType: "Physical",
    range: "All Enemies",
    tier: "D",
  },
  {
    id: "ahri",
    name: "Ahri",
    ability: "Debuff Removal",
    attackType: "Magic",
    range: "Only Basic Attack",
    tier: "D",
  },
];

export const AUTOCOMPLETE_DATABASE = HERO_DATABASE.filter(
  (h) => h.tier !== "D"
);
